# Application CMake file for OppGen3 project

set(APP_DEFINITIONS
    USE_HAL_DRIVER
    STM32F103xB
    "__weak=__attribute__((weak))"
    "__packed=__attribute__((__packed__))"
)

# === CMSIS and system sources ===
set(APP_CMSIS_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/system_stm32f1xx.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/stm32f1xx_it.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/stm32f1xx_hal_msp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/startup/startup_stm32f103xb.S
)

# === HAL driver sources ===
set(APP_HAL_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c
)

# === Middleware sources ===
set(APP_MIDDLEWARE_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c
)

# === Application sources ===
set(APP_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/main.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/usb_device.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/usbd_cdc_if.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/usbd_conf.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/usbd_desc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/debug.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/digital.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/fade.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/incand.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/lampMtrx.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/neopxl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/rs232proc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/servo.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/spiwing.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/stdldigio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/stdlflash.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/stdlser.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/Common/timer.c
)

# Path to the bootloader binary (generated by the bootloader target)
# This depends on the bootloader being built first
#set(BOOTLOADER_BIN_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../Gen3Images/Booty-TEMP.bin)
set(BOOTLOADER_BIN_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../Gen3Images/BootyStm32.0.0.bin) # newest release

# Generate the actual linker script from the template
configure_file(
    ${CMAKE_CURRENT_SOURCE_DIR}/STM32F103C8Tx_FLASH.ld.template
    ${CMAKE_CURRENT_BINARY_DIR}/STM32F103C8Tx_FLASH.ld
    @ONLY
)

# Use the generated linker script
set(APP_LINKER_SCRIPT ${CMAKE_CURRENT_BINARY_DIR}/STM32F103C8Tx_FLASH.ld)
